default:
    tags: ["Board"]
    
board check:
  stage: .pre
  script: /home/gitlab-runner/prepare.sh

compile in source:
  stage: build
  script: /home/gitlab-runner/build.sh $CI_PROJECT_DIR

testing :
  stage: test
  script:  /home/gitlab-runner/launch.sh $CI_JOB_ID $GITLAB_USER_NAME
  artifacts:
    when: always
    reports:
      junit: report.xml