default:
    tags: ["Board"]
    
job 0:
  stage: .pre
  script: echo "hola test"

job 1:
  stage: build
  script: echo "hola build"

job 2:
  stage: test
  script:  /home/gitlab-runner/launch.sh
  artifacts:
    when: always
    reports:
      junit: report.xml