default:
    tags: ["Board"]
    
job 0:
  stage: .pre
  script: /home/gitlab-runner/prepare.sh

job 1:
  stage: build
  script: /home/gitlab-runner/build.sh $CI_PROJECT_DIR

job 2:
  stage: test
  script:  /home/gitlab-runner/launch.sh $CI_JOB_ID $GITLAB_USER_NAME
  artifacts:
    when: always
    reports:
      junit: report.xml