default:
    tags: ["Board"]
    
board check:
  stage: .pre
  script: /home/gitlab-runner/prepare.sh $CI_JOB_ID $GITLAB_USER_NAME

compile in source CUDA:
  stage: build
  script: /home/gitlab-runner/build_cuda.sh $CI_PROJECT_DIR

compile in source HIP:
  stage: build
  script: /home/gitlab-runner/build_hip.sh $CI_PROJECT_DIR
 
compile in source OpenCL:
  stage: build
  script: /home/gitlab-runner/build_opencl.sh $CI_PROJECT_DIR
 
compile in source OpenMP:
  stage: build
  script: /home/gitlab-runner/build_openmp.sh $CI_PROJECT_DIR

testing cuda:
  stage: test
  script:  /home/gitlab-runner/test_cuda.sh $CI_JOB_ID $CI_PROJECT_DIR $GITLAB_USER_NAME $CI_COMMIT_BRANCH $CI_COMMIT_MESSAGE $CI_COMMIT_SHA 

testing hip:
  stage: test
  script:  /home/gitlab-runner/test_hip.sh $CI_JOB_ID $CI_PROJECT_DIR $GITLAB_USER_NAME $CI_COMMIT_BRANCH $CI_COMMIT_MESSAGE $CI_COMMIT_SHA 
      
testing opencl:
  stage: test
  script:  /home/gitlab-runner/test_opencl.sh $CI_JOB_ID $CI_PROJECT_DIR $GITLAB_USER_NAME $CI_COMMIT_BRANCH $CI_COMMIT_MESSAGE $CI_COMMIT_SHA 

testing openmp:
  stage: test
  script:  /home/gitlab-runner/test_openmp.sh $CI_JOB_ID $CI_PROJECT_DIR $GITLAB_USER_NAME $CI_COMMIT_BRANCH $CI_COMMIT_MESSAGE $CI_COMMIT_SHA 

